# Generated by Django 6.0 on 2025-12-18 03:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='courses_title_0466cc_idx'), models.Index(fields=['instructor'], name='courses_instruc_97576c_idx'), models.Index(fields=['level'], name='courses_level_838724_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='products_name_6f9890_idx'), models.Index(fields=['category'], name='products_categor_fce6e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the specific entity')),
                ('review_text', models.TextField(help_text='Original review text (Tamil or English)')),
                ('reviewer_name', models.CharField(blank=True, help_text='Name of the reviewer (optional)', max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, help_text='Email for follow-up (optional)', max_length=254)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, help_text='AI-detected sentiment', max_length=20)),
                ('polarity_score', models.FloatField(help_text='Sentiment polarity: -1 (negative) to +1 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rating', models.IntegerField(db_index=True, help_text='Auto-generated star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in sentiment prediction', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Detected language of review', max_length=10)),
                ('translated_text', models.TextField(blank=True, help_text='English translation (if original was Tamil)')),
                ('was_translated', models.BooleanField(default=False, help_text='Whether review was translated')),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Flagged as potentially fake/suspicious')),
                ('suspicious_flags', models.JSONField(blank=True, default=list, help_text='List of red flags detected')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of reviewer (for spam prevention)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent (for analytics)')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Admin approval status')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured review for homepage')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from moderators')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of entity being reviewed (Product/Course)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_content_be5f25_idx'), models.Index(fields=['sentiment', 'rating'], name='reviews_sentime_6b9c1f_idx'), models.Index(fields=['is_approved', 'created_at'], name='reviews_is_appr_fce845_idx'), models.Index(fields=['language'], name='reviews_languag_86bfed_idx'), models.Index(fields=['is_suspicious'], name='reviews_is_susp_4bf876_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('average_polarity', models.FloatField(default=0.0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('rating_5_count', models.IntegerField(default=0)),
                ('rating_4_count', models.IntegerField(default=0)),
                ('rating_3_count', models.IntegerField(default=0)),
                ('rating_2_count', models.IntegerField(default=0)),
                ('rating_1_count', models.IntegerField(default=0)),
                ('suspicious_reviews_count', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'review_summaries',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='review_summ_content_1446d1_idx'), models.Index(fields=['average_rating'], name='review_summ_average_668361_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
