# Generated by Django 6.0 on 2025-12-18 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_is_appr_fce845_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_languag_86bfed_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_is_susp_4bf876_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewsummary',
            name='review_summ_content_1446d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewsummary',
            name='review_summ_average_668361_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='confidence_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_suspicious',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='polarity_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='suspicious_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='review',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='was_translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='reviews_is_appr_807bf4_idx'),
        ),
    ]
